name: CI/CD com Hadolint

on:
  push:
    branches: [ main ]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Hadolint
        run: |
          sudo apt-get update
          sudo apt-get install -y hadolint

      - name: Analisar Dockerfile com Hadolint
        run: |
          hadolint Dockerfile

      - name: Falhar caso haja erros de Hadolint
        run: |
          exit_code=$?
          if [[ $exit_code -ne 0 ]]; then
            echo "Erros encontrados pelo Hadolint!"
            exit 1
          fi
